package test;

import org.testng.Assert;
import org.testng.annotations.Test;

import annotations.TestDataSheet;
import base.BaseTest;
import constants.UIConstants;
import dataProviders.TestDataProvider;
import datamodels.AddEmployeeData;
import datamodels.LoginData;
import pages.dashboardPage;
import pages.loginPage;
import pages.PIMPage;
import pages.addEmployeePage;

@TestDataSheet(sheetName = "AddEmployee",  model=AddEmployeeData.class)
public class addEmployeeTests extends BaseTest
{
	@Test(enabled=true, dataProvider = "TestData", dataProviderClass = TestDataProvider.class)
	public void TC08_VerifyAddEmployeewithvaliddetails(String username, String password, String firstname, String lastname) {
		loginPage login = new loginPage(driver);
		String loginPageCheck = login.isLoginPageVisible();
		Assert.assertEquals(loginPageCheck,UIConstants.LOGIN_PAGE_TITLE);
		login.enterUsernameAndPassword(username,password);
		login.clickLoginButton();	
		dashboardPage dashboard = new dashboardPage(driver);
		Assert.assertEquals(dashboard.verifyDashBoard(), UIConstants.DASHBOARD_PAGE_TITLE);		
		PIMPage pim = new PIMPage(driver);
		pim.PIMclick();
		Assert.assertEquals(pim.verifyPIM(),UIConstants.PIM_PAGE_TITLE);
		pim.clickAddEmplpyee();
		addEmployeePage addEmployee = new addEmployeePage(driver);
		Assert.assertEquals(addEmployee.addEmployeeText(), UIConstants.PIM_PAGE_ADD_EMPLOYEE_TEXT);
		addEmployee.enterFirstName(firstname);
		addEmployee.enterLastName(lastname);
		addEmployee.clickSaveButton();
		Assert.assertEquals(pim.validateEmployeeName(), firstname + " " + lastname);		
	}
	
	@Test(enabled=true, dataProvider = "TestData", dataProviderClass = TestDataProvider.class)

	public void TC09_VerifyAddEmployeeWithoutFirstName(String username, String password, String lastname)
	{
		loginPage login = new loginPage(driver);
		String loginPageCheck = login.isLoginPageVisible();
		Assert.assertEquals(loginPageCheck,UIConstants.LOGIN_PAGE_TITLE);
		login.enterUsernameAndPassword(username,password);
		login.clickLoginButton();	
		dashboardPage dashboard = new dashboardPage(driver);
		Assert.assertEquals(dashboard.verifyDashBoard(),UIConstants.DASHBOARD_PAGE_TITLE);
		PIMPage pim = new PIMPage(driver);
		pim.PIMclick();
		Assert.assertEquals(pim.verifyPIM(), UIConstants.PIM_PAGE_TITLE);
		pim.clickAddEmplpyee();
		addEmployeePage addEmployee = new addEmployeePage(driver);
		Assert.assertEquals(addEmployee.addEmployeeText(), UIConstants.PIM_PAGE_ADD_EMPLOYEE_TEXT);
		addEmployee.enterLastName(lastname);
		addEmployee.clickSaveButton();
		Assert.assertEquals(addEmployee.firstNameErrorMessage(), UIConstants.REQUIRED_TEXT);		
	}
	
	@Test(enabled=true, dataProvider = "TestData", dataProviderClass = TestDataProvider.class)
	public void TC10_VerifyAddEmployeeWithoutLastName(String username, String password, String firstname)
	{
		loginPage login = new loginPage(driver);
		String loginPageCheck = login.isLoginPageVisible();
		Assert.assertEquals(loginPageCheck,UIConstants.LOGIN_PAGE_TITLE);
		login.enterUsernameAndPassword(username,password);
		login.clickLoginButton();	
		dashboardPage dashboard = new dashboardPage(driver);
		Assert.assertEquals(dashboard.verifyDashBoard(), UIConstants.DASHBOARD_PAGE_TITLE);		
		PIMPage pim = new PIMPage(driver);
		pim.PIMclick();
		Assert.assertEquals(pim.verifyPIM(), UIConstants.PIM_PAGE_TITLE);
		pim.clickAddEmplpyee();
		addEmployeePage addEmployee = new addEmployeePage(driver);
		Assert.assertEquals(addEmployee.addEmployeeText(), UIConstants.PIM_PAGE_ADD_EMPLOYEE_TEXT);
		addEmployee.enterFirstName(firstname);
		addEmployee.clickSaveButton();
		Assert.assertEquals(addEmployee.lastNameErrorMessage(), UIConstants.REQUIRED_TEXT);		
	}
	
	@Test(enabled=true, dataProvider = "TestData", dataProviderClass = TestDataProvider.class)
	public void TC11_VerifyEmployeeIDautogenerated(String username, String password)
	{
		loginPage login = new loginPage(driver);
		String loginPageCheck = login.isLoginPageVisible();
		Assert.assertEquals(loginPageCheck,UIConstants.LOGIN_PAGE_TITLE);
		login.enterUsernameAndPassword(username,password);
		login.clickLoginButton();	
		dashboardPage dashboard = new dashboardPage(driver);
		Assert.assertEquals(dashboard.verifyDashBoard(), UIConstants.DASHBOARD_PAGE_TITLE);
		PIMPage pim = new PIMPage(driver);
		pim.PIMclick();
		Assert.assertEquals(pim.verifyPIM(), UIConstants.PIM_PAGE_TITLE);
		pim.clickAddEmplpyee();
		addEmployeePage addEmployee = new addEmployeePage(driver);
		Assert.assertEquals(addEmployee.addEmployeeText(), UIConstants.PIM_PAGE_ADD_EMPLOYEE_TEXT);
		Assert.assertNotNull(addEmployee.verifyAutoGeneratedEmployeeID(), UIConstants.PIM_PAGE_EMPLOYEE_ID_NOT_NULL);
		Assert.assertFalse(addEmployee.verifyAutoGeneratedEmployeeID().trim().isEmpty(),UIConstants.PIM_PAGE_EMPLOYEE_ID_NOT_EMPTY);
		Assert.assertTrue(addEmployee.verifyAutoGeneratedEmployeeID().matches("\\d+"),UIConstants.PIM_PAGE_EMPLOYEE_ID_ONLY_DIGITS);
	}
	
	@Test(enabled=true, dataProvider = "TestData", dataProviderClass = TestDataProvider.class)
	public void TC12_VerifyDuplicateEmployeeID(String username, String password,String empID)
	{
		loginPage login = new loginPage(driver);
		String loginPageCheck = login.isLoginPageVisible();
		Assert.assertEquals(loginPageCheck,UIConstants.LOGIN_PAGE_TITLE);
		login.enterUsernameAndPassword(username,password);
		login.clickLoginButton();	
		dashboardPage dashboard = new dashboardPage(driver);
		Assert.assertEquals(dashboard.verifyDashBoard(), UIConstants.DASHBOARD_PAGE_TITLE);		
		PIMPage pim = new PIMPage(driver);
		pim.PIMclick();
		Assert.assertEquals(pim.verifyPIM(), UIConstants.PIM_PAGE_TITLE);
		pim.clickAddEmplpyee();
		addEmployeePage addEmployee = new addEmployeePage(driver);
		Assert.assertEquals(addEmployee.addEmployeeText(), UIConstants.PIM_PAGE_ADD_EMPLOYEE_TEXT);
		addEmployee.enterExistingEmpID(empID);
		Assert.assertEquals(addEmployee.empIDErrorMessage(), UIConstants.PIM_PAGE_EMPLOYEE_ID_ALREADY_EXISTS);
	}
	
	@Test(enabled=true, dataProvider = "TestData", dataProviderClass = TestDataProvider.class)
	public void TC13_VerifyAddEmployeewithLoginDetails(String username, String password, String firstname, String lastname, String loginusername,String loginpassword)
	{
		loginPage login = new loginPage(driver);
		String loginPageCheck = login.isLoginPageVisible();
		Assert.assertEquals(loginPageCheck,UIConstants.LOGIN_PAGE_TITLE);
		login.enterUsernameAndPassword(username,password);
		login.clickLoginButton();	
		dashboardPage dashboard = new dashboardPage(driver);
		Assert.assertEquals(dashboard.verifyDashBoard(), UIConstants.DASHBOARD_PAGE_TITLE);
		PIMPage pim = new PIMPage(driver);
		pim.PIMclick();
		Assert.assertEquals(pim.verifyPIM(), UIConstants.PIM_PAGE_TITLE);
		pim.clickAddEmplpyee();
		addEmployeePage addEmployee = new addEmployeePage(driver);
		Assert.assertEquals(addEmployee.addEmployeeText(), UIConstants.PIM_PAGE_ADD_EMPLOYEE_TEXT);
		addEmployee.enterFirstName(firstname);
		addEmployee.enterLastName(lastname);
		addEmployee.switchOnLoginDetailsWrapper();
		addEmployee.enterLoginDetails(loginusername,loginpassword);
		addEmployee.clickSaveButton();
		Assert.assertEquals(pim.validateEmployeeName(), firstname + " " + lastname);
		dashboard.clickProfileDropdown();
		dashboard.clickLogoutButton();	
		Assert.assertEquals(loginPageCheck,UIConstants.LOGIN_PAGE_TITLE);
		login.enterUsernameAndPassword(loginusername,loginpassword);
		login.clickLoginButton();	
		Assert.assertEquals(pim.verifyPIM(), UIConstants.PIM_PAGE_TITLE);		
	}
	
	@Test(enabled=true, dataProvider = "TestData", dataProviderClass = TestDataProvider.class)
	public void TC14_VerifyCancelButton(String username, String password)
	{
		loginPage login = new loginPage(driver);
		String loginPageCheck = login.isLoginPageVisible();
		Assert.assertEquals(loginPageCheck,UIConstants.LOGIN_PAGE_TITLE);
		login.enterUsernameAndPassword(username,password);
		login.clickLoginButton();	
		dashboardPage dashboard = new dashboardPage(driver);
		Assert.assertEquals(dashboard.verifyDashBoard(), UIConstants.DASHBOARD_PAGE_TITLE);
		PIMPage pim = new PIMPage(driver);
		pim.PIMclick();
		Assert.assertEquals(pim.verifyPIM(), UIConstants.PIM_PAGE_TITLE);
		pim.clickAddEmplpyee();
		addEmployeePage addEmployee = new addEmployeePage(driver);
		Assert.assertEquals(addEmployee.addEmployeeText(), UIConstants.PIM_PAGE_ADD_EMPLOYEE_TEXT);
		addEmployee.clickCancelButton();
		Assert.assertEquals(pim.validateEmployeeInfoText(),UIConstants.PIM_PAGE_EMPLOYEE_INFO_TITLE);
	}
	
}