package test;

import org.testng.Assert;
import org.testng.annotations.Test;

import annotations.TestDataSheet;
import base.BaseTest;
import constants.UIConstants;
import dataProviders.TestDataProvider;
import datamodels.AddEmployeeData;
import pages.dashboardPage;
import pages.loginPage;
import pages.PIMPage;
import pages.addEmployeePage;

@TestDataSheet(sheetName = "AddEmployee",  model=AddEmployeeData.class)
public class addEmployeeTests extends BaseTest
{
	@Test(enabled=true, dataProvider = "TestData" , dataProviderClass=TestDataProvider.class)
	public void TC08_VerifyAddEmployeewithvaliddetails(AddEmployeeData data) {
		loginPage login = new loginPage(driver);
		String loginPageCheck = login.isLoginPageVisible();
		Assert.assertEquals(loginPageCheck,UIConstants.LOGIN_PAGE_TITLE);
		login.enterUsernameAndPassword(data.getUsername(),data.getPassword());
		login.clickLoginButton();	
		dashboardPage dashboard = new dashboardPage(driver);
		Assert.assertEquals(dashboard.verifyDashBoard(), UIConstants.DASHBOARD_PAGE_TITLE);		
		PIMPage pim = new PIMPage(driver);
		pim.PIMclick();
		Assert.assertEquals(pim.verifyPIM(),UIConstants.PIM_PAGE_TITLE);
		pim.clickAddEmplpyee();
		addEmployeePage addEmployee = new addEmployeePage(driver);
		Assert.assertEquals(addEmployee.addEmployeeText(), UIConstants.PIM_PAGE_ADD_EMPLOYEE_TEXT);
		addEmployee.enterFirstName(data.getFirstName());
		addEmployee.enterLastName(data.getLastName());
		addEmployee.clickSaveButton();
		Assert.assertEquals(pim.validateEmployeeName(), data.getFirstName() + " " + data.getLastName());		
	}
	
	@Test(enabled=true, dataProvider = "TestData", dataProviderClass = TestDataProvider.class)

	public void TC09_VerifyAddEmployeeWithoutFirstName(AddEmployeeData data)
	{
		loginPage login = new loginPage(driver);
		String loginPageCheck = login.isLoginPageVisible();
		Assert.assertEquals(loginPageCheck,UIConstants.LOGIN_PAGE_TITLE);
		login.enterUsernameAndPassword(data.getUsername(),data.getPassword());
		login.clickLoginButton();	
		dashboardPage dashboard = new dashboardPage(driver);
		Assert.assertEquals(dashboard.verifyDashBoard(),UIConstants.DASHBOARD_PAGE_TITLE);
		PIMPage pim = new PIMPage(driver);
		pim.PIMclick();
		Assert.assertEquals(pim.verifyPIM(), UIConstants.PIM_PAGE_TITLE);
		pim.clickAddEmplpyee();
		addEmployeePage addEmployee = new addEmployeePage(driver);
		Assert.assertEquals(addEmployee.addEmployeeText(), UIConstants.PIM_PAGE_ADD_EMPLOYEE_TEXT);
		addEmployee.enterLastName(data.getLastName());
		addEmployee.clickSaveButton();
		Assert.assertEquals(addEmployee.firstNameErrorMessage(), UIConstants.REQUIRED_TEXT);		
	}
	
	@Test(enabled=true, dataProvider = "TestData", dataProviderClass = TestDataProvider.class)
	public void TC10_VerifyAddEmployeeWithoutLastName(AddEmployeeData data)
	{
		loginPage login = new loginPage(driver);
		String loginPageCheck = login.isLoginPageVisible();
		Assert.assertEquals(loginPageCheck,UIConstants.LOGIN_PAGE_TITLE);
		login.enterUsernameAndPassword(data.getUsername(),data.getPassword());
		login.clickLoginButton();	
		dashboardPage dashboard = new dashboardPage(driver);
		Assert.assertEquals(dashboard.verifyDashBoard(), UIConstants.DASHBOARD_PAGE_TITLE);		
		PIMPage pim = new PIMPage(driver);
		pim.PIMclick();
		Assert.assertEquals(pim.verifyPIM(), UIConstants.PIM_PAGE_TITLE);
		pim.clickAddEmplpyee();
		addEmployeePage addEmployee = new addEmployeePage(driver);
		Assert.assertEquals(addEmployee.addEmployeeText(), UIConstants.PIM_PAGE_ADD_EMPLOYEE_TEXT);
		addEmployee.enterFirstName(data.getFirstName());
		addEmployee.clickSaveButton();
		Assert.assertEquals(addEmployee.lastNameErrorMessage(), UIConstants.REQUIRED_TEXT);		
	}
	
	@Test(enabled=true, dataProvider = "TestData", dataProviderClass = TestDataProvider.class)
	public void TC11_VerifyEmployeeIDautogenerated(AddEmployeeData data)
	{
		loginPage login = new loginPage(driver);
		String loginPageCheck = login.isLoginPageVisible();
		Assert.assertEquals(loginPageCheck,UIConstants.LOGIN_PAGE_TITLE);
		login.enterUsernameAndPassword(data.getUsername(),data.getPassword());
		login.clickLoginButton();	
		dashboardPage dashboard = new dashboardPage(driver);
		Assert.assertEquals(dashboard.verifyDashBoard(), UIConstants.DASHBOARD_PAGE_TITLE);
		PIMPage pim = new PIMPage(driver);
		pim.PIMclick();
		Assert.assertEquals(pim.verifyPIM(), UIConstants.PIM_PAGE_TITLE);
		pim.clickAddEmplpyee();
		addEmployeePage addEmployee = new addEmployeePage(driver);
		Assert.assertEquals(addEmployee.addEmployeeText(), UIConstants.PIM_PAGE_ADD_EMPLOYEE_TEXT);
		Assert.assertNotNull(addEmployee.verifyAutoGeneratedEmployeeID(), UIConstants.PIM_PAGE_EMPLOYEE_ID_NOT_NULL);
		Assert.assertFalse(addEmployee.verifyAutoGeneratedEmployeeID().trim().isEmpty(),UIConstants.PIM_PAGE_EMPLOYEE_ID_NOT_EMPTY);
		Assert.assertTrue(addEmployee.verifyAutoGeneratedEmployeeID().matches("\\d+"),UIConstants.PIM_PAGE_EMPLOYEE_ID_ONLY_DIGITS);
	}
	
	@Test(enabled=true, dataProvider = "TestData", dataProviderClass = TestDataProvider.class)
	public void TC12_VerifyDuplicateEmployeeID(AddEmployeeData data)
	{
		loginPage login = new loginPage(driver);
		String loginPageCheck = login.isLoginPageVisible();
		Assert.assertEquals(loginPageCheck,UIConstants.LOGIN_PAGE_TITLE);
		login.enterUsernameAndPassword(data.getUsername(),data.getPassword());
		login.clickLoginButton();	
		dashboardPage dashboard = new dashboardPage(driver);
		Assert.assertEquals(dashboard.verifyDashBoard(), UIConstants.DASHBOARD_PAGE_TITLE);		
		PIMPage pim = new PIMPage(driver);
		pim.PIMclick();
		Assert.assertEquals(pim.verifyPIM(), UIConstants.PIM_PAGE_TITLE);
		pim.clickAddEmplpyee();
		addEmployeePage addEmployee = new addEmployeePage(driver);
		Assert.assertEquals(addEmployee.addEmployeeText(), UIConstants.PIM_PAGE_ADD_EMPLOYEE_TEXT);
		addEmployee.enterExistingEmpID(data.getEmpID());
		Assert.assertEquals(addEmployee.empIDErrorMessage(), UIConstants.PIM_PAGE_EMPLOYEE_ID_ALREADY_EXISTS);
	}
	
	@Test(enabled=true, dataProvider = "TestData", dataProviderClass = TestDataProvider.class)
	public void TC13_VerifyAddEmployeewithLoginDetails(AddEmployeeData data)
	{
		loginPage login = new loginPage(driver);
		String loginPageCheck = login.isLoginPageVisible();
		Assert.assertEquals(loginPageCheck,UIConstants.LOGIN_PAGE_TITLE);
		login.enterUsernameAndPassword(data.getUsername(),data.getPassword());
		login.clickLoginButton();	
		dashboardPage dashboard = new dashboardPage(driver);
		Assert.assertEquals(dashboard.verifyDashBoard(), UIConstants.DASHBOARD_PAGE_TITLE);
		PIMPage pim = new PIMPage(driver);
		pim.PIMclick();
		Assert.assertEquals(pim.verifyPIM(), UIConstants.PIM_PAGE_TITLE);
		pim.clickAddEmplpyee();
		addEmployeePage addEmployee = new addEmployeePage(driver);
		Assert.assertEquals(addEmployee.addEmployeeText(), UIConstants.PIM_PAGE_ADD_EMPLOYEE_TEXT);
		addEmployee.enterFirstName(data.getFirstName());
		addEmployee.enterLastName(data.getLastName());
		addEmployee.switchOnLoginDetailsWrapper();
		addEmployee.enterLoginDetails(data.getLoginUserName(),data.getLoginPassword());
		addEmployee.clickSaveButton();
		Assert.assertEquals(pim.validateEmployeeName(), data.getFirstName() + " " + data.getLastName());
		dashboard.clickProfileDropdown();
		dashboard.clickLogoutButton();	
		Assert.assertEquals(loginPageCheck,UIConstants.LOGIN_PAGE_TITLE);
		login.enterUsernameAndPassword(data.getLoginUserName(),data.getLoginPassword());
		login.clickLoginButton();	
		Assert.assertEquals(dashboard.verifyDashBoard(), UIConstants.DASHBOARD_PAGE_TITLE);
	}
	
	@Test(enabled=true, dataProvider = "TestData", dataProviderClass = TestDataProvider.class)
	public void TC14_VerifyCancelButton(AddEmployeeData data)
	{
		loginPage login = new loginPage(driver);
		String loginPageCheck = login.isLoginPageVisible();
		Assert.assertEquals(loginPageCheck,UIConstants.LOGIN_PAGE_TITLE);
		login.enterUsernameAndPassword(data.getUsername(),data.getPassword());
		login.clickLoginButton();	
		dashboardPage dashboard = new dashboardPage(driver);
		Assert.assertEquals(dashboard.verifyDashBoard(), UIConstants.DASHBOARD_PAGE_TITLE);
		PIMPage pim = new PIMPage(driver);
		pim.PIMclick();
		Assert.assertEquals(pim.verifyPIM(), UIConstants.PIM_PAGE_TITLE);
		pim.clickAddEmplpyee();
		addEmployeePage addEmployee = new addEmployeePage(driver);
		Assert.assertEquals(addEmployee.addEmployeeText(), UIConstants.PIM_PAGE_ADD_EMPLOYEE_TEXT);
		addEmployee.clickCancelButton();
		Assert.assertEquals(pim.validateEmployeeInfoText(),UIConstants.PIM_PAGE_EMPLOYEE_INFO_TITLE);
	}
	
}