package test;

import org.testng.Assert;
import org.testng.annotations.Test;
import base.DriverFactory;
import pages.dashboardPage;
import pages.loginPage;
import pages.PIMPage;
import pages.addEmployeePage;

public class addEmployeeTests extends DriverFactory
{
	@Test(enabled=false)
	public void TC08_VerifyAddEmployeewithvaliddetails() {
		loginPage login = new loginPage(driver);
		String loginPageCheck = login.isLoginPageVisible();
		Assert.assertEquals(loginPageCheck,"Login");
		login.enterUsernameAndPassword("Admin","admin123");
		login.clickLoginButton();	
		dashboardPage dashboard = new dashboardPage(driver);
		Assert.assertEquals(dashboard.verifyDashBoard(), "Dashboard");
		dashboard.PIMclick();
		PIMPage pim = new PIMPage(driver);
		Assert.assertEquals(pim.verifyPIM(), "PIM");
		pim.clickAddEmplpyee();
		addEmployeePage addEmployee = new addEmployeePage(driver);
		Assert.assertEquals(addEmployee.addEmployeeText(), "Add Employee");
		addEmployee.enterFirstName("testcheck123");
		addEmployee.enterLastName("test");
		addEmployee.clickSaveButton();
		Assert.assertEquals(pim.validateEmployeeName(), "testcheck123 test");		
	}
	
	@Test(enabled=false)
	public void TC09_VerifyAddEmployeeWithoutFirstName()
	{
		loginPage login = new loginPage(driver);
		String loginPageCheck = login.isLoginPageVisible();
		Assert.assertEquals(loginPageCheck,"Login");
		login.enterUsernameAndPassword("Admin","admin123");
		login.clickLoginButton();	
		dashboardPage dashboard = new dashboardPage(driver);
		Assert.assertEquals(dashboard.verifyDashBoard(), "Dashboard");
		dashboard.PIMclick();
		PIMPage pim = new PIMPage(driver);
		Assert.assertEquals(pim.verifyPIM(), "PIM");
		pim.clickAddEmplpyee();
		addEmployeePage addEmployee = new addEmployeePage(driver);
		Assert.assertEquals(addEmployee.addEmployeeText(), "Add Employee");
		addEmployee.enterLastName("test");
		addEmployee.clickSaveButton();
		Assert.assertEquals(addEmployee.firstNameErrorMessage(), "Required");		
	}
	
	@Test(enabled=false)
	public void TC10_VerifyAddEmployeeWithoutLastName()
	{
		loginPage login = new loginPage(driver);
		String loginPageCheck = login.isLoginPageVisible();
		Assert.assertEquals(loginPageCheck,"Login");
		login.enterUsernameAndPassword("Admin","admin123");
		login.clickLoginButton();	
		dashboardPage dashboard = new dashboardPage(driver);
		Assert.assertEquals(dashboard.verifyDashBoard(), "Dashboard");
		dashboard.PIMclick();
		PIMPage pim = new PIMPage(driver);
		Assert.assertEquals(pim.verifyPIM(), "PIM");
		pim.clickAddEmplpyee();
		addEmployeePage addEmployee = new addEmployeePage(driver);
		Assert.assertEquals(addEmployee.addEmployeeText(), "Add Employee");
		addEmployee.enterFirstName("testcheck123");
		addEmployee.clickSaveButton();
		Assert.assertEquals(addEmployee.lastNameErrorMessage(), "Required");		
	}
	
	@Test(enabled=false)
	public void TC11_VerifyEmployeeIDautogenerated()
	{
		loginPage login = new loginPage(driver);
		String loginPageCheck = login.isLoginPageVisible();
		Assert.assertEquals(loginPageCheck,"Login");
		login.enterUsernameAndPassword("Admin","admin123");
		login.clickLoginButton();	
		dashboardPage dashboard = new dashboardPage(driver);
		Assert.assertEquals(dashboard.verifyDashBoard(), "Dashboard");
		dashboard.PIMclick();
		PIMPage pim = new PIMPage(driver);
		Assert.assertEquals(pim.verifyPIM(), "PIM");
		pim.clickAddEmplpyee();
		addEmployeePage addEmployee = new addEmployeePage(driver);
		Assert.assertEquals(addEmployee.addEmployeeText(), "Add Employee");
		Assert.assertNotNull(addEmployee.verifyAutoGeneratedEmployeeID(), "Employee ID should not be null");
		Assert.assertFalse(addEmployee.verifyAutoGeneratedEmployeeID().trim().isEmpty(),"Employee ID should not be empty");
		Assert.assertTrue(addEmployee.verifyAutoGeneratedEmployeeID().matches("\\d+"),"Employee ID should contain only digits");
	}
	
	@Test(enabled=false)
	public void TC12_VerifyDuplicateEmployeeID()
	{
		loginPage login = new loginPage(driver);
		String loginPageCheck = login.isLoginPageVisible();
		Assert.assertEquals(loginPageCheck,"Login");
		login.enterUsernameAndPassword("Admin","admin123");
		login.clickLoginButton();	
		dashboardPage dashboard = new dashboardPage(driver);
		Assert.assertEquals(dashboard.verifyDashBoard(), "Dashboard");
		dashboard.PIMclick();
		PIMPage pim = new PIMPage(driver);
		Assert.assertEquals(pim.verifyPIM(), "PIM");
		pim.clickAddEmplpyee();
		addEmployeePage addEmployee = new addEmployeePage(driver);
		Assert.assertEquals(addEmployee.addEmployeeText(), "Add Employee");
		addEmployee.enterExistingEmpID("0401");
		Assert.assertEquals(addEmployee.empIDErrorMessage(), "Employee Id already exists");
	}
	
	@Test(enabled=false)
	public void TC13_VerifyAddEmployeewithLoginDetails()
	{
		loginPage login = new loginPage(driver);
		String loginPageCheck = login.isLoginPageVisible();
		Assert.assertEquals(loginPageCheck,"Login");
		login.enterUsernameAndPassword("Admin","admin123");
		login.clickLoginButton();	
		dashboardPage dashboard = new dashboardPage(driver);
		Assert.assertEquals(dashboard.verifyDashBoard(), "Dashboard");
		dashboard.PIMclick();
		PIMPage pim = new PIMPage(driver);
		Assert.assertEquals(pim.verifyPIM(), "PIM");
		pim.clickAddEmplpyee();
		addEmployeePage addEmployee = new addEmployeePage(driver);
		Assert.assertEquals(addEmployee.addEmployeeText(), "Add Employee");
		addEmployee.enterFirstName("testcheck");
		addEmployee.enterLastName("test");
		addEmployee.switchOnLoginDetailsWrapper();
		addEmployee.enterLoginDetails("testcheck1","testcheck1");
		addEmployee.clickSaveButton();
		Assert.assertEquals(pim.validateEmployeeName(), "testcheck test");
		dashboard.clickProfileDropdown();
		dashboard.clickLogoutButton();	
		Assert.assertEquals(loginPageCheck,"Login");
		login.enterUsernameAndPassword("testcheck1","testcheck1");
		login.clickLoginButton();	
		Assert.assertEquals(pim.verifyPIM(), "PIM");		
	}
	
	@Test(enabled=false)
	public void TC14_VerifyCancelButton()
	{
		loginPage login = new loginPage(driver);
		String loginPageCheck = login.isLoginPageVisible();
		Assert.assertEquals(loginPageCheck,"Login");
		login.enterUsernameAndPassword("Admin","admin123");
		login.clickLoginButton();	
		dashboardPage dashboard = new dashboardPage(driver);
		Assert.assertEquals(dashboard.verifyDashBoard(), "Dashboard");
		dashboard.PIMclick();
		PIMPage pim = new PIMPage(driver);
		Assert.assertEquals(pim.verifyPIM(), "PIM");
		pim.clickAddEmplpyee();
		addEmployeePage addEmployee = new addEmployeePage(driver);
		Assert.assertEquals(addEmployee.addEmployeeText(), "Add Employee");
		addEmployee.clickCancelButton();
		Assert.assertEquals(pim.validateEmployeeInfoText(),"Employee Information");
	}
	
}