package pages;

import java.time.Duration;

import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Keys;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.support.FindBy;
import org.openqa.selenium.support.PageFactory;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;

public class addEmployeePage
{
	WebDriver driver;
	
	@FindBy(xpath="//h6[@class=\"oxd-text oxd-text--h6 orangehrm-main-title\"]")
	WebElement addEmplpyeeText;
	@FindBy(xpath="//input[@name=\"firstName\"]")
	WebElement firstnametxtbox;
	@FindBy(xpath="//input[@name=\"lastName\"]")
	WebElement lastnametxtbox;
	@FindBy(xpath="//button[@class=\"oxd-button oxd-button--medium oxd-button--secondary orangehrm-left-space\"]")
	WebElement saveButton;
	@FindBy(xpath="//input[@name=\"firstName\"]/../..//span[@class=\"oxd-text oxd-text--span oxd-input-field-error-message oxd-input-group__message\"]")
	WebElement firstNameErrorText;
	@FindBy(xpath="//input[@name=\"lastName\"]/../..//span[@class=\"oxd-text oxd-text--span oxd-input-field-error-message oxd-input-group__message\"]")
	WebElement lastNameErrorText;
	@FindBy(xpath="//label[text()='Employee Id']/following::input[1]")
	WebElement empIDField;
	@FindBy(xpath="//label[text()='Employee Id']/following::span[1]")
	WebElement empIDErrorText;
	@FindBy(xpath="//p[text()=\"Create Login Details\"]/..//input[@type=\"checkbox\"]//following-sibling::span")
	WebElement loginDetailsSwtich;
	@FindBy(xpath="//label[text()=\"Username\"]/..//following-sibling::div//input[@class=\"oxd-input oxd-input--active\"]")
	WebElement userNameTextBox;
	@FindBy(xpath="//input[@type=\"password\"]")
	WebElement passwordTextBox;
	@FindBy(xpath="//label[text()=\"Confirm Password\"]/..//following-sibling::div//input[@type=\"password\"]")
	WebElement confirmPasswordTextBox;
	@FindBy(xpath="//button[text()=\" Cancel \"]")
	WebElement cancelButton;
	
	
	public addEmployeePage(WebDriver driver)
	{
		this.driver = driver;
		PageFactory.initElements(driver, this);
	}
	
	public String addEmployeeText()
	{
		return addEmplpyeeText.getText();
	}
	
	public void enterFirstName(String firstname)
	{
		WebDriverWait wait = new WebDriverWait(driver,Duration.ofSeconds(10));
		wait.until(ExpectedConditions.visibilityOf(firstnametxtbox));
		firstnametxtbox.sendKeys(firstname);
	}
	
	public void enterLastName(String lastname)
	{
		lastnametxtbox.sendKeys(lastname);
	}
	
	public void clickSaveButton()
	{
		JavascriptExecutor js = (JavascriptExecutor) driver;
		js.executeScript("arguments[0].scrollIntoView();", saveButton);	
		saveButton.click();
	}
	
	public String firstNameErrorMessage()
	{
		return firstNameErrorText.getText();
	}
	
	public String lastNameErrorMessage()
	{
		return lastNameErrorText.getText();
	}
	
	public String verifyAutoGeneratedEmployeeID()
	{		
		JavascriptExecutor js = (JavascriptExecutor) driver;
		String value = (String) js.executeScript(
		    "return arguments[0].value;", empIDField);
		return value;
	}
	
	public void enterExistingEmpID(String empID)
	{
		empIDField.click();
		empIDField.sendKeys(Keys.CONTROL + "a");
		empIDField.sendKeys(Keys.DELETE);
		empIDField.sendKeys(empID);
		empIDField.sendKeys(Keys.TAB);
	}
	
	public String empIDErrorMessage()
	{
		WebDriverWait wait = new WebDriverWait(driver,Duration.ofSeconds(30));
		wait.until(ExpectedConditions.textToBePresentInElement(empIDErrorText, "Employee Id already exists"));
		return empIDErrorText.getText();
	}
	
	public void switchOnLoginDetailsWrapper()
	{
		JavascriptExecutor js = (JavascriptExecutor) driver;
		js.executeScript("arguments[0].click();", loginDetailsSwtich);
	}
	
	public void enterLoginDetails(String username, String password)
	{
		WebDriverWait wait = new WebDriverWait(driver,Duration.ofSeconds(30));
		wait.until(ExpectedConditions.visibilityOf(userNameTextBox));
		userNameTextBox.sendKeys(username);
		passwordTextBox.sendKeys(password);
		confirmPasswordTextBox.sendKeys(password);		
	}
	
	public void clickCancelButton()
	{
		cancelButton.click();
	}
	
}